name: CVWeatherTimeControl
version: 1.21
main: org.cubeville.cvweathertimecontrol.CVWeatherTimeControl
api-version: 1.21
depend: [Vault,CVIPC]
commands:
  instasun:
    description: Buy instant nice weather
    permission: cvweathercontrol

  instastorm:
    description: Buy a storm
    permission: cvweathercontrol

  instaday:
    description: Make it morning
    permission: cvweathercontrol

  instanight:
    description: Make it night
    permission: cvweathercontrol
